/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_phonex_util_crypto_NativeCryptoHelper */

#ifndef _Included_net_phonex_util_crypto_NativeCryptoHelper
#define _Included_net_phonex_util_crypto_NativeCryptoHelper
#ifdef __cplusplus
extern "C" {
#endif
#undef net_phonex_util_crypto_NativeCryptoHelper_HMAC_SHA1
#define net_phonex_util_crypto_NativeCryptoHelper_HMAC_SHA1 1L
#undef net_phonex_util_crypto_NativeCryptoHelper_HMAC_SHA256
#define net_phonex_util_crypto_NativeCryptoHelper_HMAC_SHA256 2L
/*
 * Class:     net_phonex_util_crypto_NativeCryptoHelper
 * Method:    pbkdf2
 * Signature: (Ljava/lang/String;[BII[BII)I
 */
JNIEXPORT jint JNICALL Java_net_phonex_util_crypto_NativeCryptoHelper_pbkdf2
  (JNIEnv *, jobject, jstring, jbyteArray, jint, jint, jbyteArray, jint, jint);

/*
 * Class:     net_phonex_util_crypto_NativeCryptoHelper
 * Method:    scrypt
 * Signature: ([BI[BIIII[BI)I
 */
JNIEXPORT jint JNICALL Java_net_phonex_util_crypto_NativeCryptoHelper_scrypt
  (JNIEnv *, jobject, jbyteArray, jint, jbyteArray, jint, jint, jint, jint, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
