/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_phonex_util_crypto_NativeCryptoHelper */

#ifndef _Included_net_phonex_util_crypto_NativeCryptoHelper
#define _Included_net_phonex_util_crypto_NativeCryptoHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_phonex_util_crypto_NativeCryptoHelper
 * Method:    pbkdf2_hmac_sha256
 * Signature: (Ljava/lang/String;[BII[BI)I
 */
JNIEXPORT jint JNICALL Java_net_phonex_util_crypto_NativeCryptoHelper_pbkdf2_1hmac_1sha256
  (JNIEnv *, jobject, jstring, jbyteArray, jint, jint, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
