// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: autologin.proto

package net.phonex.pub.proto;

public final class AutoLogin {
  private AutoLogin() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface AutoLoginDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:net.phonex.pub.proto.AutoLoginData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required bytes passwordEncrypted = 1;</code>
     */
    boolean hasPasswordEncrypted();
    /**
     * <code>required bytes passwordEncrypted = 1;</code>
     */
    com.google.protobuf.ByteString getPasswordEncrypted();

    /**
     * <code>required bytes iv = 2;</code>
     */
    boolean hasIv();
    /**
     * <code>required bytes iv = 2;</code>
     */
    com.google.protobuf.ByteString getIv();

    /**
     * <code>required bytes nonce = 3;</code>
     */
    boolean hasNonce();
    /**
     * <code>required bytes nonce = 3;</code>
     */
    com.google.protobuf.ByteString getNonce();

    /**
     * <code>required bytes userName = 4;</code>
     */
    boolean hasUserName();
    /**
     * <code>required bytes userName = 4;</code>
     */
    com.google.protobuf.ByteString getUserName();

    /**
     * <code>optional bytes credsEncrypted = 5;</code>
     */
    boolean hasCredsEncrypted();
    /**
     * <code>optional bytes credsEncrypted = 5;</code>
     */
    com.google.protobuf.ByteString getCredsEncrypted();
  }
  /**
   * Protobuf type {@code net.phonex.pub.proto.AutoLoginData}
   */
  public static final class AutoLoginData extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:net.phonex.pub.proto.AutoLoginData)
      AutoLoginDataOrBuilder {
    // Use AutoLoginData.newBuilder() to construct.
    private AutoLoginData(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private AutoLoginData(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final AutoLoginData defaultInstance;
    public static AutoLoginData getDefaultInstance() {
      return defaultInstance;
    }

    public AutoLoginData getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private AutoLoginData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              passwordEncrypted_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              iv_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              nonce_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              userName_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              credsEncrypted_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.phonex.pub.proto.AutoLogin.internal_static_net_phonex_pub_proto_AutoLoginData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.phonex.pub.proto.AutoLogin.internal_static_net_phonex_pub_proto_AutoLoginData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.phonex.pub.proto.AutoLogin.AutoLoginData.class, net.phonex.pub.proto.AutoLogin.AutoLoginData.Builder.class);
    }

    public static com.google.protobuf.Parser<AutoLoginData> PARSER =
        new com.google.protobuf.AbstractParser<AutoLoginData>() {
      public AutoLoginData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AutoLoginData(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<AutoLoginData> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int PASSWORDENCRYPTED_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString passwordEncrypted_;
    /**
     * <code>required bytes passwordEncrypted = 1;</code>
     */
    public boolean hasPasswordEncrypted() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required bytes passwordEncrypted = 1;</code>
     */
    public com.google.protobuf.ByteString getPasswordEncrypted() {
      return passwordEncrypted_;
    }

    public static final int IV_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString iv_;
    /**
     * <code>required bytes iv = 2;</code>
     */
    public boolean hasIv() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required bytes iv = 2;</code>
     */
    public com.google.protobuf.ByteString getIv() {
      return iv_;
    }

    public static final int NONCE_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString nonce_;
    /**
     * <code>required bytes nonce = 3;</code>
     */
    public boolean hasNonce() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required bytes nonce = 3;</code>
     */
    public com.google.protobuf.ByteString getNonce() {
      return nonce_;
    }

    public static final int USERNAME_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString userName_;
    /**
     * <code>required bytes userName = 4;</code>
     */
    public boolean hasUserName() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required bytes userName = 4;</code>
     */
    public com.google.protobuf.ByteString getUserName() {
      return userName_;
    }

    public static final int CREDSENCRYPTED_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString credsEncrypted_;
    /**
     * <code>optional bytes credsEncrypted = 5;</code>
     */
    public boolean hasCredsEncrypted() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional bytes credsEncrypted = 5;</code>
     */
    public com.google.protobuf.ByteString getCredsEncrypted() {
      return credsEncrypted_;
    }

    private void initFields() {
      passwordEncrypted_ = com.google.protobuf.ByteString.EMPTY;
      iv_ = com.google.protobuf.ByteString.EMPTY;
      nonce_ = com.google.protobuf.ByteString.EMPTY;
      userName_ = com.google.protobuf.ByteString.EMPTY;
      credsEncrypted_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasPasswordEncrypted()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasIv()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasNonce()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasUserName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, passwordEncrypted_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, iv_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, nonce_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, userName_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, credsEncrypted_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, passwordEncrypted_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, iv_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, nonce_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, userName_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, credsEncrypted_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static net.phonex.pub.proto.AutoLogin.AutoLoginData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.phonex.pub.proto.AutoLogin.AutoLoginData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.phonex.pub.proto.AutoLogin.AutoLoginData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.phonex.pub.proto.AutoLogin.AutoLoginData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.phonex.pub.proto.AutoLogin.AutoLoginData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static net.phonex.pub.proto.AutoLogin.AutoLoginData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static net.phonex.pub.proto.AutoLogin.AutoLoginData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static net.phonex.pub.proto.AutoLogin.AutoLoginData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static net.phonex.pub.proto.AutoLogin.AutoLoginData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static net.phonex.pub.proto.AutoLogin.AutoLoginData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(net.phonex.pub.proto.AutoLogin.AutoLoginData prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code net.phonex.pub.proto.AutoLoginData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:net.phonex.pub.proto.AutoLoginData)
        net.phonex.pub.proto.AutoLogin.AutoLoginDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.phonex.pub.proto.AutoLogin.internal_static_net_phonex_pub_proto_AutoLoginData_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.phonex.pub.proto.AutoLogin.internal_static_net_phonex_pub_proto_AutoLoginData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.phonex.pub.proto.AutoLogin.AutoLoginData.class, net.phonex.pub.proto.AutoLogin.AutoLoginData.Builder.class);
      }

      // Construct using net.phonex.pub.proto.AutoLogin.AutoLoginData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        passwordEncrypted_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        iv_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        nonce_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        userName_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        credsEncrypted_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.phonex.pub.proto.AutoLogin.internal_static_net_phonex_pub_proto_AutoLoginData_descriptor;
      }

      public net.phonex.pub.proto.AutoLogin.AutoLoginData getDefaultInstanceForType() {
        return net.phonex.pub.proto.AutoLogin.AutoLoginData.getDefaultInstance();
      }

      public net.phonex.pub.proto.AutoLogin.AutoLoginData build() {
        net.phonex.pub.proto.AutoLogin.AutoLoginData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public net.phonex.pub.proto.AutoLogin.AutoLoginData buildPartial() {
        net.phonex.pub.proto.AutoLogin.AutoLoginData result = new net.phonex.pub.proto.AutoLogin.AutoLoginData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.passwordEncrypted_ = passwordEncrypted_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.iv_ = iv_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.nonce_ = nonce_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.userName_ = userName_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.credsEncrypted_ = credsEncrypted_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.phonex.pub.proto.AutoLogin.AutoLoginData) {
          return mergeFrom((net.phonex.pub.proto.AutoLogin.AutoLoginData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(net.phonex.pub.proto.AutoLogin.AutoLoginData other) {
        if (other == net.phonex.pub.proto.AutoLogin.AutoLoginData.getDefaultInstance()) return this;
        if (other.hasPasswordEncrypted()) {
          setPasswordEncrypted(other.getPasswordEncrypted());
        }
        if (other.hasIv()) {
          setIv(other.getIv());
        }
        if (other.hasNonce()) {
          setNonce(other.getNonce());
        }
        if (other.hasUserName()) {
          setUserName(other.getUserName());
        }
        if (other.hasCredsEncrypted()) {
          setCredsEncrypted(other.getCredsEncrypted());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasPasswordEncrypted()) {
          
          return false;
        }
        if (!hasIv()) {
          
          return false;
        }
        if (!hasNonce()) {
          
          return false;
        }
        if (!hasUserName()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        net.phonex.pub.proto.AutoLogin.AutoLoginData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (net.phonex.pub.proto.AutoLogin.AutoLoginData) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString passwordEncrypted_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes passwordEncrypted = 1;</code>
       */
      public boolean hasPasswordEncrypted() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required bytes passwordEncrypted = 1;</code>
       */
      public com.google.protobuf.ByteString getPasswordEncrypted() {
        return passwordEncrypted_;
      }
      /**
       * <code>required bytes passwordEncrypted = 1;</code>
       */
      public Builder setPasswordEncrypted(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        passwordEncrypted_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes passwordEncrypted = 1;</code>
       */
      public Builder clearPasswordEncrypted() {
        bitField0_ = (bitField0_ & ~0x00000001);
        passwordEncrypted_ = getDefaultInstance().getPasswordEncrypted();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString iv_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes iv = 2;</code>
       */
      public boolean hasIv() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required bytes iv = 2;</code>
       */
      public com.google.protobuf.ByteString getIv() {
        return iv_;
      }
      /**
       * <code>required bytes iv = 2;</code>
       */
      public Builder setIv(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        iv_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes iv = 2;</code>
       */
      public Builder clearIv() {
        bitField0_ = (bitField0_ & ~0x00000002);
        iv_ = getDefaultInstance().getIv();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString nonce_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes nonce = 3;</code>
       */
      public boolean hasNonce() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required bytes nonce = 3;</code>
       */
      public com.google.protobuf.ByteString getNonce() {
        return nonce_;
      }
      /**
       * <code>required bytes nonce = 3;</code>
       */
      public Builder setNonce(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        nonce_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes nonce = 3;</code>
       */
      public Builder clearNonce() {
        bitField0_ = (bitField0_ & ~0x00000004);
        nonce_ = getDefaultInstance().getNonce();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString userName_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes userName = 4;</code>
       */
      public boolean hasUserName() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required bytes userName = 4;</code>
       */
      public com.google.protobuf.ByteString getUserName() {
        return userName_;
      }
      /**
       * <code>required bytes userName = 4;</code>
       */
      public Builder setUserName(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        userName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes userName = 4;</code>
       */
      public Builder clearUserName() {
        bitField0_ = (bitField0_ & ~0x00000008);
        userName_ = getDefaultInstance().getUserName();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString credsEncrypted_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes credsEncrypted = 5;</code>
       */
      public boolean hasCredsEncrypted() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional bytes credsEncrypted = 5;</code>
       */
      public com.google.protobuf.ByteString getCredsEncrypted() {
        return credsEncrypted_;
      }
      /**
       * <code>optional bytes credsEncrypted = 5;</code>
       */
      public Builder setCredsEncrypted(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        credsEncrypted_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes credsEncrypted = 5;</code>
       */
      public Builder clearCredsEncrypted() {
        bitField0_ = (bitField0_ & ~0x00000010);
        credsEncrypted_ = getDefaultInstance().getCredsEncrypted();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:net.phonex.pub.proto.AutoLoginData)
    }

    static {
      defaultInstance = new AutoLoginData(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:net.phonex.pub.proto.AutoLoginData)
  }

  public interface AutoLoginCredsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:net.phonex.pub.proto.AutoLoginCreds)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required bytes password = 1;</code>
     */
    boolean hasPassword();
    /**
     * <code>required bytes password = 1;</code>
     */
    com.google.protobuf.ByteString getPassword();

    /**
     * <code>required bytes sip = 2;</code>
     */
    boolean hasSip();
    /**
     * <code>required bytes sip = 2;</code>
     */
    com.google.protobuf.ByteString getSip();
  }
  /**
   * Protobuf type {@code net.phonex.pub.proto.AutoLoginCreds}
   */
  public static final class AutoLoginCreds extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:net.phonex.pub.proto.AutoLoginCreds)
      AutoLoginCredsOrBuilder {
    // Use AutoLoginCreds.newBuilder() to construct.
    private AutoLoginCreds(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private AutoLoginCreds(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final AutoLoginCreds defaultInstance;
    public static AutoLoginCreds getDefaultInstance() {
      return defaultInstance;
    }

    public AutoLoginCreds getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private AutoLoginCreds(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              password_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              sip_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.phonex.pub.proto.AutoLogin.internal_static_net_phonex_pub_proto_AutoLoginCreds_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.phonex.pub.proto.AutoLogin.internal_static_net_phonex_pub_proto_AutoLoginCreds_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.phonex.pub.proto.AutoLogin.AutoLoginCreds.class, net.phonex.pub.proto.AutoLogin.AutoLoginCreds.Builder.class);
    }

    public static com.google.protobuf.Parser<AutoLoginCreds> PARSER =
        new com.google.protobuf.AbstractParser<AutoLoginCreds>() {
      public AutoLoginCreds parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AutoLoginCreds(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<AutoLoginCreds> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int PASSWORD_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString password_;
    /**
     * <code>required bytes password = 1;</code>
     */
    public boolean hasPassword() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required bytes password = 1;</code>
     */
    public com.google.protobuf.ByteString getPassword() {
      return password_;
    }

    public static final int SIP_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString sip_;
    /**
     * <code>required bytes sip = 2;</code>
     */
    public boolean hasSip() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required bytes sip = 2;</code>
     */
    public com.google.protobuf.ByteString getSip() {
      return sip_;
    }

    private void initFields() {
      password_ = com.google.protobuf.ByteString.EMPTY;
      sip_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasPassword()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSip()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, password_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, sip_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, password_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, sip_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static net.phonex.pub.proto.AutoLogin.AutoLoginCreds parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.phonex.pub.proto.AutoLogin.AutoLoginCreds parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.phonex.pub.proto.AutoLogin.AutoLoginCreds parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.phonex.pub.proto.AutoLogin.AutoLoginCreds parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.phonex.pub.proto.AutoLogin.AutoLoginCreds parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static net.phonex.pub.proto.AutoLogin.AutoLoginCreds parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static net.phonex.pub.proto.AutoLogin.AutoLoginCreds parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static net.phonex.pub.proto.AutoLogin.AutoLoginCreds parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static net.phonex.pub.proto.AutoLogin.AutoLoginCreds parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static net.phonex.pub.proto.AutoLogin.AutoLoginCreds parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(net.phonex.pub.proto.AutoLogin.AutoLoginCreds prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code net.phonex.pub.proto.AutoLoginCreds}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:net.phonex.pub.proto.AutoLoginCreds)
        net.phonex.pub.proto.AutoLogin.AutoLoginCredsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.phonex.pub.proto.AutoLogin.internal_static_net_phonex_pub_proto_AutoLoginCreds_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.phonex.pub.proto.AutoLogin.internal_static_net_phonex_pub_proto_AutoLoginCreds_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.phonex.pub.proto.AutoLogin.AutoLoginCreds.class, net.phonex.pub.proto.AutoLogin.AutoLoginCreds.Builder.class);
      }

      // Construct using net.phonex.pub.proto.AutoLogin.AutoLoginCreds.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        password_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        sip_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.phonex.pub.proto.AutoLogin.internal_static_net_phonex_pub_proto_AutoLoginCreds_descriptor;
      }

      public net.phonex.pub.proto.AutoLogin.AutoLoginCreds getDefaultInstanceForType() {
        return net.phonex.pub.proto.AutoLogin.AutoLoginCreds.getDefaultInstance();
      }

      public net.phonex.pub.proto.AutoLogin.AutoLoginCreds build() {
        net.phonex.pub.proto.AutoLogin.AutoLoginCreds result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public net.phonex.pub.proto.AutoLogin.AutoLoginCreds buildPartial() {
        net.phonex.pub.proto.AutoLogin.AutoLoginCreds result = new net.phonex.pub.proto.AutoLogin.AutoLoginCreds(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.password_ = password_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.sip_ = sip_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.phonex.pub.proto.AutoLogin.AutoLoginCreds) {
          return mergeFrom((net.phonex.pub.proto.AutoLogin.AutoLoginCreds)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(net.phonex.pub.proto.AutoLogin.AutoLoginCreds other) {
        if (other == net.phonex.pub.proto.AutoLogin.AutoLoginCreds.getDefaultInstance()) return this;
        if (other.hasPassword()) {
          setPassword(other.getPassword());
        }
        if (other.hasSip()) {
          setSip(other.getSip());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasPassword()) {
          
          return false;
        }
        if (!hasSip()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        net.phonex.pub.proto.AutoLogin.AutoLoginCreds parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (net.phonex.pub.proto.AutoLogin.AutoLoginCreds) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString password_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes password = 1;</code>
       */
      public boolean hasPassword() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required bytes password = 1;</code>
       */
      public com.google.protobuf.ByteString getPassword() {
        return password_;
      }
      /**
       * <code>required bytes password = 1;</code>
       */
      public Builder setPassword(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        password_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes password = 1;</code>
       */
      public Builder clearPassword() {
        bitField0_ = (bitField0_ & ~0x00000001);
        password_ = getDefaultInstance().getPassword();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString sip_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes sip = 2;</code>
       */
      public boolean hasSip() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required bytes sip = 2;</code>
       */
      public com.google.protobuf.ByteString getSip() {
        return sip_;
      }
      /**
       * <code>required bytes sip = 2;</code>
       */
      public Builder setSip(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        sip_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes sip = 2;</code>
       */
      public Builder clearSip() {
        bitField0_ = (bitField0_ & ~0x00000002);
        sip_ = getDefaultInstance().getSip();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:net.phonex.pub.proto.AutoLoginCreds)
    }

    static {
      defaultInstance = new AutoLoginCreds(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:net.phonex.pub.proto.AutoLoginCreds)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_net_phonex_pub_proto_AutoLoginData_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_net_phonex_pub_proto_AutoLoginData_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_net_phonex_pub_proto_AutoLoginCreds_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_net_phonex_pub_proto_AutoLoginCreds_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017autologin.proto\022\024net.phonex.pub.proto\"" +
      "o\n\rAutoLoginData\022\031\n\021passwordEncrypted\030\001 " +
      "\002(\014\022\n\n\002iv\030\002 \002(\014\022\r\n\005nonce\030\003 \002(\014\022\020\n\010userNa" +
      "me\030\004 \002(\014\022\026\n\016credsEncrypted\030\005 \001(\014\"/\n\016Auto" +
      "LoginCreds\022\020\n\010password\030\001 \002(\014\022\013\n\003sip\030\002 \002(" +
      "\014B\rB\tAutoLoginH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_net_phonex_pub_proto_AutoLoginData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_net_phonex_pub_proto_AutoLoginData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_net_phonex_pub_proto_AutoLoginData_descriptor,
        new java.lang.String[] { "PasswordEncrypted", "Iv", "Nonce", "UserName", "CredsEncrypted", });
    internal_static_net_phonex_pub_proto_AutoLoginCreds_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_net_phonex_pub_proto_AutoLoginCreds_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_net_phonex_pub_proto_AutoLoginCreds_descriptor,
        new java.lang.String[] { "Password", "Sip", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
