// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rest.proto

package net.phonex.pub.proto;

public final class ServerProtoBuff {
  private ServerProtoBuff() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface RESTUploadPostOrBuilder extends
      // @@protoc_insertion_point(interface_extends:net.phonex.pub.proto.RESTUploadPost)
      com.google.protobuf.GeneratedMessage.
          ExtendableMessageOrBuilder<RESTUploadPost> {

    /**
     * <code>required uint32 version = 1 [default = 1];</code>
     */
    boolean hasVersion();
    /**
     * <code>required uint32 version = 1 [default = 1];</code>
     */
    int getVersion();

    /**
     * <code>optional int32 errorCode = 2;</code>
     */
    boolean hasErrorCode();
    /**
     * <code>optional int32 errorCode = 2;</code>
     */
    int getErrorCode();

    /**
     * <code>optional string message = 3;</code>
     */
    boolean hasMessage();
    /**
     * <code>optional string message = 3;</code>
     */
    java.lang.String getMessage();
    /**
     * <code>optional string message = 3;</code>
     */
    com.google.protobuf.ByteString
        getMessageBytes();

    /**
     * <code>optional string nonce2 = 4;</code>
     */
    boolean hasNonce2();
    /**
     * <code>optional string nonce2 = 4;</code>
     */
    java.lang.String getNonce2();
    /**
     * <code>optional string nonce2 = 4;</code>
     */
    com.google.protobuf.ByteString
        getNonce2Bytes();

    /**
     * <code>optional uint64 length = 5;</code>
     *
     * <pre>
     * Length of a transfered file.
     * </pre>
     */
    boolean hasLength();
    /**
     * <code>optional uint64 length = 5;</code>
     *
     * <pre>
     * Length of a transfered file.
     * </pre>
     */
    long getLength();
  }
  /**
   * Protobuf type {@code net.phonex.pub.proto.RESTUploadPost}
   *
   * <pre>
   * Message sent as a response to the HTTPS POST file upload. 
   * </pre>
   */
  public static final class RESTUploadPost extends
      com.google.protobuf.GeneratedMessage.ExtendableMessage<
        RESTUploadPost> implements
      // @@protoc_insertion_point(message_implements:net.phonex.pub.proto.RESTUploadPost)
      RESTUploadPostOrBuilder {
    // Use RESTUploadPost.newBuilder() to construct.
    private RESTUploadPost(com.google.protobuf.GeneratedMessage.ExtendableBuilder<net.phonex.pub.proto.ServerProtoBuff.RESTUploadPost, ?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RESTUploadPost(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RESTUploadPost defaultInstance;
    public static RESTUploadPost getDefaultInstance() {
      return defaultInstance;
    }

    public RESTUploadPost getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RESTUploadPost(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              version_ = input.readUInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              errorCode_ = input.readInt32();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              message_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              nonce2_ = bs;
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              length_ = input.readUInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.phonex.pub.proto.ServerProtoBuff.internal_static_net_phonex_pub_proto_RESTUploadPost_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.phonex.pub.proto.ServerProtoBuff.internal_static_net_phonex_pub_proto_RESTUploadPost_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.phonex.pub.proto.ServerProtoBuff.RESTUploadPost.class, net.phonex.pub.proto.ServerProtoBuff.RESTUploadPost.Builder.class);
    }

    public static com.google.protobuf.Parser<RESTUploadPost> PARSER =
        new com.google.protobuf.AbstractParser<RESTUploadPost>() {
      public RESTUploadPost parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RESTUploadPost(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<RESTUploadPost> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int VERSION_FIELD_NUMBER = 1;
    private int version_;
    /**
     * <code>required uint32 version = 1 [default = 1];</code>
     */
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint32 version = 1 [default = 1];</code>
     */
    public int getVersion() {
      return version_;
    }

    public static final int ERRORCODE_FIELD_NUMBER = 2;
    private int errorCode_;
    /**
     * <code>optional int32 errorCode = 2;</code>
     */
    public boolean hasErrorCode() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 errorCode = 2;</code>
     */
    public int getErrorCode() {
      return errorCode_;
    }

    public static final int MESSAGE_FIELD_NUMBER = 3;
    private java.lang.Object message_;
    /**
     * <code>optional string message = 3;</code>
     */
    public boolean hasMessage() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string message = 3;</code>
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          message_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string message = 3;</code>
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NONCE2_FIELD_NUMBER = 4;
    private java.lang.Object nonce2_;
    /**
     * <code>optional string nonce2 = 4;</code>
     */
    public boolean hasNonce2() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string nonce2 = 4;</code>
     */
    public java.lang.String getNonce2() {
      java.lang.Object ref = nonce2_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          nonce2_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string nonce2 = 4;</code>
     */
    public com.google.protobuf.ByteString
        getNonce2Bytes() {
      java.lang.Object ref = nonce2_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nonce2_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LENGTH_FIELD_NUMBER = 5;
    private long length_;
    /**
     * <code>optional uint64 length = 5;</code>
     *
     * <pre>
     * Length of a transfered file.
     * </pre>
     */
    public boolean hasLength() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional uint64 length = 5;</code>
     *
     * <pre>
     * Length of a transfered file.
     * </pre>
     */
    public long getLength() {
      return length_;
    }

    private void initFields() {
      version_ = 1;
      errorCode_ = 0;
      message_ = "";
      nonce2_ = "";
      length_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasVersion()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!extensionsAreInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      com.google.protobuf.GeneratedMessage
        .ExtendableMessage<net.phonex.pub.proto.ServerProtoBuff.RESTUploadPost>.ExtensionWriter extensionWriter =
          newExtensionWriter();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, version_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, errorCode_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getMessageBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getNonce2Bytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeUInt64(5, length_);
      }
      extensionWriter.writeUntil(1000, output);
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, version_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, errorCode_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getMessageBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getNonce2Bytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(5, length_);
      }
      size += extensionsSerializedSize();
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static net.phonex.pub.proto.ServerProtoBuff.RESTUploadPost parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.phonex.pub.proto.ServerProtoBuff.RESTUploadPost parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.phonex.pub.proto.ServerProtoBuff.RESTUploadPost parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.phonex.pub.proto.ServerProtoBuff.RESTUploadPost parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.phonex.pub.proto.ServerProtoBuff.RESTUploadPost parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static net.phonex.pub.proto.ServerProtoBuff.RESTUploadPost parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static net.phonex.pub.proto.ServerProtoBuff.RESTUploadPost parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static net.phonex.pub.proto.ServerProtoBuff.RESTUploadPost parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static net.phonex.pub.proto.ServerProtoBuff.RESTUploadPost parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static net.phonex.pub.proto.ServerProtoBuff.RESTUploadPost parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(net.phonex.pub.proto.ServerProtoBuff.RESTUploadPost prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code net.phonex.pub.proto.RESTUploadPost}
     *
     * <pre>
     * Message sent as a response to the HTTPS POST file upload. 
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.ExtendableBuilder<
          net.phonex.pub.proto.ServerProtoBuff.RESTUploadPost, Builder> implements
        // @@protoc_insertion_point(builder_implements:net.phonex.pub.proto.RESTUploadPost)
        net.phonex.pub.proto.ServerProtoBuff.RESTUploadPostOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.phonex.pub.proto.ServerProtoBuff.internal_static_net_phonex_pub_proto_RESTUploadPost_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.phonex.pub.proto.ServerProtoBuff.internal_static_net_phonex_pub_proto_RESTUploadPost_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.phonex.pub.proto.ServerProtoBuff.RESTUploadPost.class, net.phonex.pub.proto.ServerProtoBuff.RESTUploadPost.Builder.class);
      }

      // Construct using net.phonex.pub.proto.ServerProtoBuff.RESTUploadPost.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        version_ = 1;
        bitField0_ = (bitField0_ & ~0x00000001);
        errorCode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        message_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        nonce2_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        length_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.phonex.pub.proto.ServerProtoBuff.internal_static_net_phonex_pub_proto_RESTUploadPost_descriptor;
      }

      public net.phonex.pub.proto.ServerProtoBuff.RESTUploadPost getDefaultInstanceForType() {
        return net.phonex.pub.proto.ServerProtoBuff.RESTUploadPost.getDefaultInstance();
      }

      public net.phonex.pub.proto.ServerProtoBuff.RESTUploadPost build() {
        net.phonex.pub.proto.ServerProtoBuff.RESTUploadPost result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public net.phonex.pub.proto.ServerProtoBuff.RESTUploadPost buildPartial() {
        net.phonex.pub.proto.ServerProtoBuff.RESTUploadPost result = new net.phonex.pub.proto.ServerProtoBuff.RESTUploadPost(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.version_ = version_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.errorCode_ = errorCode_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.message_ = message_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.nonce2_ = nonce2_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.length_ = length_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.phonex.pub.proto.ServerProtoBuff.RESTUploadPost) {
          return mergeFrom((net.phonex.pub.proto.ServerProtoBuff.RESTUploadPost)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(net.phonex.pub.proto.ServerProtoBuff.RESTUploadPost other) {
        if (other == net.phonex.pub.proto.ServerProtoBuff.RESTUploadPost.getDefaultInstance()) return this;
        if (other.hasVersion()) {
          setVersion(other.getVersion());
        }
        if (other.hasErrorCode()) {
          setErrorCode(other.getErrorCode());
        }
        if (other.hasMessage()) {
          bitField0_ |= 0x00000004;
          message_ = other.message_;
          onChanged();
        }
        if (other.hasNonce2()) {
          bitField0_ |= 0x00000008;
          nonce2_ = other.nonce2_;
          onChanged();
        }
        if (other.hasLength()) {
          setLength(other.getLength());
        }
        this.mergeExtensionFields(other);
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasVersion()) {
          
          return false;
        }
        if (!extensionsAreInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        net.phonex.pub.proto.ServerProtoBuff.RESTUploadPost parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (net.phonex.pub.proto.ServerProtoBuff.RESTUploadPost) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int version_ = 1;
      /**
       * <code>required uint32 version = 1 [default = 1];</code>
       */
      public boolean hasVersion() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint32 version = 1 [default = 1];</code>
       */
      public int getVersion() {
        return version_;
      }
      /**
       * <code>required uint32 version = 1 [default = 1];</code>
       */
      public Builder setVersion(int value) {
        bitField0_ |= 0x00000001;
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 version = 1 [default = 1];</code>
       */
      public Builder clearVersion() {
        bitField0_ = (bitField0_ & ~0x00000001);
        version_ = 1;
        onChanged();
        return this;
      }

      private int errorCode_ ;
      /**
       * <code>optional int32 errorCode = 2;</code>
       */
      public boolean hasErrorCode() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 errorCode = 2;</code>
       */
      public int getErrorCode() {
        return errorCode_;
      }
      /**
       * <code>optional int32 errorCode = 2;</code>
       */
      public Builder setErrorCode(int value) {
        bitField0_ |= 0x00000002;
        errorCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 errorCode = 2;</code>
       */
      public Builder clearErrorCode() {
        bitField0_ = (bitField0_ & ~0x00000002);
        errorCode_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object message_ = "";
      /**
       * <code>optional string message = 3;</code>
       */
      public boolean hasMessage() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string message = 3;</code>
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            message_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string message = 3;</code>
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string message = 3;</code>
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string message = 3;</code>
       */
      public Builder clearMessage() {
        bitField0_ = (bitField0_ & ~0x00000004);
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      /**
       * <code>optional string message = 3;</code>
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        message_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object nonce2_ = "";
      /**
       * <code>optional string nonce2 = 4;</code>
       */
      public boolean hasNonce2() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string nonce2 = 4;</code>
       */
      public java.lang.String getNonce2() {
        java.lang.Object ref = nonce2_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            nonce2_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string nonce2 = 4;</code>
       */
      public com.google.protobuf.ByteString
          getNonce2Bytes() {
        java.lang.Object ref = nonce2_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nonce2_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string nonce2 = 4;</code>
       */
      public Builder setNonce2(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        nonce2_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string nonce2 = 4;</code>
       */
      public Builder clearNonce2() {
        bitField0_ = (bitField0_ & ~0x00000008);
        nonce2_ = getDefaultInstance().getNonce2();
        onChanged();
        return this;
      }
      /**
       * <code>optional string nonce2 = 4;</code>
       */
      public Builder setNonce2Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        nonce2_ = value;
        onChanged();
        return this;
      }

      private long length_ ;
      /**
       * <code>optional uint64 length = 5;</code>
       *
       * <pre>
       * Length of a transfered file.
       * </pre>
       */
      public boolean hasLength() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional uint64 length = 5;</code>
       *
       * <pre>
       * Length of a transfered file.
       * </pre>
       */
      public long getLength() {
        return length_;
      }
      /**
       * <code>optional uint64 length = 5;</code>
       *
       * <pre>
       * Length of a transfered file.
       * </pre>
       */
      public Builder setLength(long value) {
        bitField0_ |= 0x00000010;
        length_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 length = 5;</code>
       *
       * <pre>
       * Length of a transfered file.
       * </pre>
       */
      public Builder clearLength() {
        bitField0_ = (bitField0_ & ~0x00000010);
        length_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:net.phonex.pub.proto.RESTUploadPost)
    }

    static {
      defaultInstance = new RESTUploadPost(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:net.phonex.pub.proto.RESTUploadPost)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_net_phonex_pub_proto_RESTUploadPost_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_net_phonex_pub_proto_RESTUploadPost_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nrest.proto\022\024net.phonex.pub.proto\"p\n\016RE" +
      "STUploadPost\022\022\n\007version\030\001 \002(\r:\0011\022\021\n\terro" +
      "rCode\030\002 \001(\005\022\017\n\007message\030\003 \001(\t\022\016\n\006nonce2\030\004" +
      " \001(\t\022\016\n\006length\030\005 \001(\004*\006\010\254\002\020\350\007B\023B\017ServerPr" +
      "otoBuffH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_net_phonex_pub_proto_RESTUploadPost_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_net_phonex_pub_proto_RESTUploadPost_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_net_phonex_pub_proto_RESTUploadPost_descriptor,
        new java.lang.String[] { "Version", "ErrorCode", "Message", "Nonce2", "Length", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
