/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.phonex.xv;

public class esign_descriptor {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected esign_descriptor(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(esign_descriptor obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        XviJNI.delete_esign_descriptor(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setPool(pj_pool_t value) {
    XviJNI.esign_descriptor_pool_set(swigCPtr, this, pj_pool_t.getCPtr(value), value);
  }

  public pj_pool_t getPool() {
    long cPtr = XviJNI.esign_descriptor_pool_get(swigCPtr, this);
    return (cPtr == 0) ? null : new pj_pool_t(cPtr, false);
  }

  public void setMod(SWIGTYPE_p_pjsip_module value) {
    XviJNI.esign_descriptor_mod_set(swigCPtr, this, SWIGTYPE_p_pjsip_module.getCPtr(value));
  }

  public SWIGTYPE_p_pjsip_module getMod() {
    long cPtr = XviJNI.esign_descriptor_mod_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_pjsip_module(cPtr, false);
  }

  public void setEndpt(SWIGTYPE_p_pjsip_endpoint value) {
    XviJNI.esign_descriptor_endpt_set(swigCPtr, this, SWIGTYPE_p_pjsip_endpoint.getCPtr(value));
  }

  public SWIGTYPE_p_pjsip_endpoint getEndpt() {
    long cPtr = XviJNI.esign_descriptor_endpt_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_pjsip_endpoint(cPtr, false);
  }

  public void setSign_info(esign_process_info value) {
    XviJNI.esign_descriptor_sign_info_set(swigCPtr, this, esign_process_info.getCPtr(value), value);
  }

  public esign_process_info getSign_info() {
    long cPtr = XviJNI.esign_descriptor_sign_info_get(swigCPtr, this);
    return (cPtr == 0) ? null : new esign_process_info(cPtr, false);
  }

  public void setMod_data(SWIGTYPE_p_p_void value) {
    XviJNI.esign_descriptor_mod_data_set(swigCPtr, this, SWIGTYPE_p_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_p_void getMod_data() {
    long cPtr = XviJNI.esign_descriptor_mod_data_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_void(cPtr, false);
  }

  public esign_descriptor() {
    this(XviJNI.new_esign_descriptor(), true);
  }

}
