/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.phonex.xv;

public class esignInfo_t {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected esignInfo_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(esignInfo_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        XviJNI.delete_esignInfo_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setIsRequest(int value) {
    XviJNI.esignInfo_t_isRequest_set(swigCPtr, this, value);
  }

  public int getIsRequest() {
    return XviJNI.esignInfo_t_isRequest_get(swigCPtr, this);
  }

  public void setCseqInt(int value) {
    XviJNI.esignInfo_t_cseqInt_set(swigCPtr, this, value);
  }

  public int getCseqInt() {
    return XviJNI.esignInfo_t_cseqInt_get(swigCPtr, this);
  }

  public void setMethod(pj_str_t value) {
    XviJNI.esignInfo_t_method_set(swigCPtr, this, pj_str_t.getCPtr(value), value);
  }

  public pj_str_t getMethod() {
    long cPtr = XviJNI.esignInfo_t_method_get(swigCPtr, this);
    return (cPtr == 0) ? null : new pj_str_t(cPtr, false);
  }

  public void setResp_status(int value) {
    XviJNI.esignInfo_t_resp_status_set(swigCPtr, this, value);
  }

  public int getResp_status() {
    return XviJNI.esignInfo_t_resp_status_get(swigCPtr, this);
  }

  public void setCseqStr(pj_str_t value) {
    XviJNI.esignInfo_t_cseqStr_set(swigCPtr, this, pj_str_t.getCPtr(value), value);
  }

  public pj_str_t getCseqStr() {
    long cPtr = XviJNI.esignInfo_t_cseqStr_get(swigCPtr, this);
    return (cPtr == 0) ? null : new pj_str_t(cPtr, false);
  }

  public void setReqUriStr(pj_str_t value) {
    XviJNI.esignInfo_t_reqUriStr_set(swigCPtr, this, pj_str_t.getCPtr(value), value);
  }

  public pj_str_t getReqUriStr() {
    long cPtr = XviJNI.esignInfo_t_reqUriStr_get(swigCPtr, this);
    return (cPtr == 0) ? null : new pj_str_t(cPtr, false);
  }

  public void setFromUriStr(pj_str_t value) {
    XviJNI.esignInfo_t_fromUriStr_set(swigCPtr, this, pj_str_t.getCPtr(value), value);
  }

  public pj_str_t getFromUriStr() {
    long cPtr = XviJNI.esignInfo_t_fromUriStr_get(swigCPtr, this);
    return (cPtr == 0) ? null : new pj_str_t(cPtr, false);
  }

  public void setToUriStr(pj_str_t value) {
    XviJNI.esignInfo_t_toUriStr_set(swigCPtr, this, pj_str_t.getCPtr(value), value);
  }

  public pj_str_t getToUriStr() {
    long cPtr = XviJNI.esignInfo_t_toUriStr_get(swigCPtr, this);
    return (cPtr == 0) ? null : new pj_str_t(cPtr, false);
  }

  public void setBodyStr(pj_str_t value) {
    XviJNI.esignInfo_t_bodyStr_set(swigCPtr, this, pj_str_t.getCPtr(value), value);
  }

  public pj_str_t getBodyStr() {
    long cPtr = XviJNI.esignInfo_t_bodyStr_get(swigCPtr, this);
    return (cPtr == 0) ? null : new pj_str_t(cPtr, false);
  }

  public void setBodySha256Str(pj_str_t value) {
    XviJNI.esignInfo_t_bodySha256Str_set(swigCPtr, this, pj_str_t.getCPtr(value), value);
  }

  public pj_str_t getBodySha256Str() {
    long cPtr = XviJNI.esignInfo_t_bodySha256Str_get(swigCPtr, this);
    return (cPtr == 0) ? null : new pj_str_t(cPtr, false);
  }

  public void setAccumStr(pj_str_t value) {
    XviJNI.esignInfo_t_accumStr_set(swigCPtr, this, pj_str_t.getCPtr(value), value);
  }

  public pj_str_t getAccumStr() {
    long cPtr = XviJNI.esignInfo_t_accumStr_get(swigCPtr, this);
    return (cPtr == 0) ? null : new pj_str_t(cPtr, false);
  }

  public void setAccumSha256Str(pj_str_t value) {
    XviJNI.esignInfo_t_accumSha256Str_set(swigCPtr, this, pj_str_t.getCPtr(value), value);
  }

  public pj_str_t getAccumSha256Str() {
    long cPtr = XviJNI.esignInfo_t_accumSha256Str_get(swigCPtr, this);
    return (cPtr == 0) ? null : new pj_str_t(cPtr, false);
  }

  public void setIp(pj_str_t value) {
    XviJNI.esignInfo_t_ip_set(swigCPtr, this, pj_str_t.getCPtr(value), value);
  }

  public pj_str_t getIp() {
    long cPtr = XviJNI.esignInfo_t_ip_get(swigCPtr, this);
    return (cPtr == 0) ? null : new pj_str_t(cPtr, false);
  }

  public esignInfo_t() {
    this(XviJNI.new_esignInfo_t(), true);
  }

}
