/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.phonex.xv;

public enum esign_sign_err_e {
  ESIGN_SIGN_ERR_SUCCESS(XviJNI.ESIGN_SIGN_ERR_SUCCESS_get()),
  ESIGN_SIGN_ERR_GENERIC,
  ESIGN_SIGN_ERR_VERSION_UNKNOWN,
  ESIGN_SIGN_ERR_LOCAL_USER_UNKNOWN,
  ESIGN_SIGN_ERR_REMOTE_USER_UNKNOWN,
  ESIGN_SIGN_ERR_REMOTE_USER_CERT_MISSING,
  ESIGN_SIGN_ERR_REMOTE_USER_CERT_ERR,
  ESIGN_SIGN_ERR_SIGNATURE_INVALID,
  ESIGN_SIGN_ERR_MAX;

  public final int swigValue() {
    return swigValue;
  }

  public static esign_sign_err_e swigToEnum(int swigValue) {
    esign_sign_err_e[] swigValues = esign_sign_err_e.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (esign_sign_err_e swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + esign_sign_err_e.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private esign_sign_err_e() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private esign_sign_err_e(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private esign_sign_err_e(esign_sign_err_e swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

