/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.phonex.xv;

public enum esign_process_state_e {
  ESIGN_PROCESS_STATE_NULL(XviJNI.ESIGN_PROCESS_STATE_NULL_get()),
  ESIGN_PROCESS_STATE_ERROR,
  ESIGN_PROCESS_STATE_PROCESSED;

  public final int swigValue() {
    return swigValue;
  }

  public static esign_process_state_e swigToEnum(int swigValue) {
    esign_process_state_e[] swigValues = esign_process_state_e.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (esign_process_state_e swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + esign_process_state_e.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private esign_process_state_e() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private esign_process_state_e(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private esign_process_state_e(esign_process_state_e swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

