/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.phonex.xv;

public class esign_process_info {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected esign_process_info(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(esign_process_info obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        XviJNI.delete_esign_process_info(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setProcess_state(esign_process_state_e value) {
    XviJNI.esign_process_info_process_state_set(swigCPtr, this, value.swigValue());
  }

  public esign_process_state_e getProcess_state() {
    return esign_process_state_e.swigToEnum(XviJNI.esign_process_info_process_state_get(swigCPtr, this));
  }

  public void setSignature_present(int value) {
    XviJNI.esign_process_info_signature_present_set(swigCPtr, this, value);
  }

  public int getSignature_present() {
    return XviJNI.esign_process_info_signature_present_get(swigCPtr, this);
  }

  public void setCallback_return(SWIGTYPE_p_pj_int16_t value) {
    XviJNI.esign_process_info_callback_return_set(swigCPtr, this, SWIGTYPE_p_pj_int16_t.getCPtr(value));
  }

  public SWIGTYPE_p_pj_int16_t getCallback_return() {
    return new SWIGTYPE_p_pj_int16_t(XviJNI.esign_process_info_callback_return_get(swigCPtr, this), true);
  }

  public void setVerify_err(esign_sign_err_e value) {
    XviJNI.esign_process_info_verify_err_set(swigCPtr, this, value.swigValue());
  }

  public esign_sign_err_e getVerify_err() {
    return esign_sign_err_e.swigToEnum(XviJNI.esign_process_info_verify_err_get(swigCPtr, this));
  }

  public void setSignature_valid(int value) {
    XviJNI.esign_process_info_signature_valid_set(swigCPtr, this, value);
  }

  public int getSignature_valid() {
    return XviJNI.esign_process_info_signature_valid_get(swigCPtr, this);
  }

  public void setPacket_dropped(int value) {
    XviJNI.esign_process_info_packet_dropped_set(swigCPtr, this, value);
  }

  public int getPacket_dropped() {
    return XviJNI.esign_process_info_packet_dropped_get(swigCPtr, this);
  }

  public void setIs_request(int value) {
    XviJNI.esign_process_info_is_request_set(swigCPtr, this, value);
  }

  public int getIs_request() {
    return XviJNI.esign_process_info_is_request_get(swigCPtr, this);
  }

  public void setMethod(pj_str_t value) {
    XviJNI.esign_process_info_method_set(swigCPtr, this, pj_str_t.getCPtr(value), value);
  }

  public pj_str_t getMethod() {
    long cPtr = XviJNI.esign_process_info_method_get(swigCPtr, this);
    return (cPtr == 0) ? null : new pj_str_t(cPtr, false);
  }

  public void setCseq_int(SWIGTYPE_p_pj_int32_t value) {
    XviJNI.esign_process_info_cseq_int_set(swigCPtr, this, SWIGTYPE_p_pj_int32_t.getCPtr(value));
  }

  public SWIGTYPE_p_pj_int32_t getCseq_int() {
    return new SWIGTYPE_p_pj_int32_t(XviJNI.esign_process_info_cseq_int_get(swigCPtr, this), true);
  }

  public void setCseq_str(pj_str_t value) {
    XviJNI.esign_process_info_cseq_str_set(swigCPtr, this, pj_str_t.getCPtr(value), value);
  }

  public pj_str_t getCseq_str() {
    long cPtr = XviJNI.esign_process_info_cseq_str_get(swigCPtr, this);
    return (cPtr == 0) ? null : new pj_str_t(cPtr, false);
  }

  public void setReq_uri_str(pj_str_t value) {
    XviJNI.esign_process_info_req_uri_str_set(swigCPtr, this, pj_str_t.getCPtr(value), value);
  }

  public pj_str_t getReq_uri_str() {
    long cPtr = XviJNI.esign_process_info_req_uri_str_get(swigCPtr, this);
    return (cPtr == 0) ? null : new pj_str_t(cPtr, false);
  }

  public void setFrom_uri_str(pj_str_t value) {
    XviJNI.esign_process_info_from_uri_str_set(swigCPtr, this, pj_str_t.getCPtr(value), value);
  }

  public pj_str_t getFrom_uri_str() {
    long cPtr = XviJNI.esign_process_info_from_uri_str_get(swigCPtr, this);
    return (cPtr == 0) ? null : new pj_str_t(cPtr, false);
  }

  public void setTo_uri_str(pj_str_t value) {
    XviJNI.esign_process_info_to_uri_str_set(swigCPtr, this, pj_str_t.getCPtr(value), value);
  }

  public pj_str_t getTo_uri_str() {
    long cPtr = XviJNI.esign_process_info_to_uri_str_get(swigCPtr, this);
    return (cPtr == 0) ? null : new pj_str_t(cPtr, false);
  }

  public void setBody_sha_256_str(pj_str_t value) {
    XviJNI.esign_process_info_body_sha_256_str_set(swigCPtr, this, pj_str_t.getCPtr(value), value);
  }

  public pj_str_t getBody_sha_256_str() {
    long cPtr = XviJNI.esign_process_info_body_sha_256_str_get(swigCPtr, this);
    return (cPtr == 0) ? null : new pj_str_t(cPtr, false);
  }

  public void setAccum_sha_256_str(pj_str_t value) {
    XviJNI.esign_process_info_accum_sha_256_str_set(swigCPtr, this, pj_str_t.getCPtr(value), value);
  }

  public pj_str_t getAccum_sha_256_str() {
    long cPtr = XviJNI.esign_process_info_accum_sha_256_str_get(swigCPtr, this);
    return (cPtr == 0) ? null : new pj_str_t(cPtr, false);
  }

  public void setStatus_code(int value) {
    XviJNI.esign_process_info_status_code_set(swigCPtr, this, value);
  }

  public int getStatus_code() {
    return XviJNI.esign_process_info_status_code_get(swigCPtr, this);
  }

  public void setSign(pj_str_t value) {
    XviJNI.esign_process_info_sign_set(swigCPtr, this, pj_str_t.getCPtr(value), value);
  }

  public pj_str_t getSign() {
    long cPtr = XviJNI.esign_process_info_sign_get(swigCPtr, this);
    return (cPtr == 0) ? null : new pj_str_t(cPtr, false);
  }

  public void setSign_desc(pj_str_t value) {
    XviJNI.esign_process_info_sign_desc_set(swigCPtr, this, pj_str_t.getCPtr(value), value);
  }

  public pj_str_t getSign_desc() {
    long cPtr = XviJNI.esign_process_info_sign_desc_get(swigCPtr, this);
    return (cPtr == 0) ? null : new pj_str_t(cPtr, false);
  }

  public esign_process_info() {
    this(XviJNI.new_esign_process_info(), true);
  }

}
