/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.phonex.xv;

public class hashReturn_t {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected hashReturn_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(hashReturn_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        XviJNI.delete_hashReturn_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setRetStatus(int value) {
    XviJNI.hashReturn_t_retStatus_set(swigCPtr, this, value);
  }

  public int getRetStatus() {
    return XviJNI.hashReturn_t_retStatus_get(swigCPtr, this);
  }

  public void setErrCode(int value) {
    XviJNI.hashReturn_t_errCode_set(swigCPtr, this, value);
  }

  public int getErrCode() {
    return XviJNI.hashReturn_t_errCode_get(swigCPtr, this);
  }

  public void setHash(pj_str_t value) {
    XviJNI.hashReturn_t_hash_set(swigCPtr, this, pj_str_t.getCPtr(value), value);
  }

  public pj_str_t getHash() {
    long cPtr = XviJNI.hashReturn_t_hash_get(swigCPtr, this);
    return (cPtr == 0) ? null : new pj_str_t(cPtr, false);
  }

  public void setDesc(pj_str_t value) {
    XviJNI.hashReturn_t_desc_set(swigCPtr, this, pj_str_t.getCPtr(value), value);
  }

  public pj_str_t getDesc() {
    long cPtr = XviJNI.hashReturn_t_desc_get(swigCPtr, this);
    return (cPtr == 0) ? null : new pj_str_t(cPtr, false);
  }

  public hashReturn_t() {
    this(XviJNI.new_hashReturn_t(), true);
  }

}
