/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.phonex.xv;

public enum pj_ice_cand_type {
  PJ_ICE_CAND_TYPE_HOST,
  PJ_ICE_CAND_TYPE_SRFLX,
  PJ_ICE_CAND_TYPE_PRFLX,
  PJ_ICE_CAND_TYPE_RELAYED,
  PJ_ICE_CAND_TYPE_MAX;

  public final int swigValue() {
    return swigValue;
  }

  public static pj_ice_cand_type swigToEnum(int swigValue) {
    pj_ice_cand_type[] swigValues = pj_ice_cand_type.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (pj_ice_cand_type swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + pj_ice_cand_type.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private pj_ice_cand_type() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private pj_ice_cand_type(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private pj_ice_cand_type(pj_ice_cand_type swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

