/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.phonex.xv;

public class pj_reg_backoff_struct {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected pj_reg_backoff_struct(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(pj_reg_backoff_struct obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        XviJNI.delete_pj_reg_backoff_struct(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setAttempt_cnt(long value) {
    XviJNI.pj_reg_backoff_struct_attempt_cnt_set(swigCPtr, this, value);
  }

  public long getAttempt_cnt() {
    return XviJNI.pj_reg_backoff_struct_attempt_cnt_get(swigCPtr, this);
  }

  public void setDelay(pj_time_val value) {
    XviJNI.pj_reg_backoff_struct_delay_set(swigCPtr, this, pj_time_val.getCPtr(value), value);
  }

  public pj_time_val getDelay() {
    long cPtr = XviJNI.pj_reg_backoff_struct_delay_get(swigCPtr, this);
    return (cPtr == 0) ? null : new pj_time_val(cPtr, false);
  }

  public pj_reg_backoff_struct() {
    this(XviJNI.new_pj_reg_backoff_struct(), true);
  }

}
