/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.phonex.xv;

public class pjsip_transport_state_info {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected pjsip_transport_state_info(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(pjsip_transport_state_info obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        XviJNI.delete_pjsip_transport_state_info(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setStatus(int value) {
    XviJNI.pjsip_transport_state_info_status_set(swigCPtr, this, value);
  }

  public int getStatus() {
    return XviJNI.pjsip_transport_state_info_status_get(swigCPtr, this);
  }

  public void setExt_info(byte[] value) {
    XviJNI.pjsip_transport_state_info_ext_info_set(swigCPtr, this, value);
  }

  public byte[] getExt_info() {
	return XviJNI.pjsip_transport_state_info_ext_info_get(swigCPtr, this);
}

  public void setUser_data(byte[] value) {
    XviJNI.pjsip_transport_state_info_user_data_set(swigCPtr, this, value);
  }

  public byte[] getUser_data() {
	return XviJNI.pjsip_transport_state_info_user_data_get(swigCPtr, this);
}

  public pjsip_transport_state_info() {
    this(XviJNI.new_pjsip_transport_state_info(), true);
  }

}
