/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.phonex.xv;

public class pjsip_event {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected pjsip_event(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(pjsip_event obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        XviJNI.delete_pjsip_event(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setType(pjsip_event_id_e value) {
    XviJNI.pjsip_event_type_set(swigCPtr, this, value.swigValue());
  }

  public pjsip_event_id_e getType() {
    return pjsip_event_id_e.swigToEnum(XviJNI.pjsip_event_type_get(swigCPtr, this));
  }

  public pjsip_event() {
    this(XviJNI.new_pjsip_event(), true);
  }

}
