/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.phonex.xv;

public enum pjsip_transport_state {
  PJSIP_TP_STATE_CONNECTED,
  PJSIP_TP_STATE_DISCONNECTED,
  PJSIP_TP_STATE_SHUTDOWN,
  PJSIP_TP_STATE_DESTROY;

  public final int swigValue() {
    return swigValue;
  }

  public static pjsip_transport_state swigToEnum(int swigValue) {
    pjsip_transport_state[] swigValues = pjsip_transport_state.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (pjsip_transport_state swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + pjsip_transport_state.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private pjsip_transport_state() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private pjsip_transport_state(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private pjsip_transport_state(pjsip_transport_state swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

