/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.phonex.xv;

public class pjsip_regc_cbparam {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected pjsip_regc_cbparam(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(pjsip_regc_cbparam obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        XviJNI.delete_pjsip_regc_cbparam(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setRegc(SWIGTYPE_p_pjsip_regc value) {
    XviJNI.pjsip_regc_cbparam_regc_set(swigCPtr, this, SWIGTYPE_p_pjsip_regc.getCPtr(value));
  }

  public SWIGTYPE_p_pjsip_regc getRegc() {
    long cPtr = XviJNI.pjsip_regc_cbparam_regc_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_pjsip_regc(cPtr, false);
  }

  public void setToken(byte[] value) {
    XviJNI.pjsip_regc_cbparam_token_set(swigCPtr, this, value);
  }

  public byte[] getToken() {
	return XviJNI.pjsip_regc_cbparam_token_get(swigCPtr, this);
}

  public void setStatus(int value) {
    XviJNI.pjsip_regc_cbparam_status_set(swigCPtr, this, value);
  }

  public int getStatus() {
    return XviJNI.pjsip_regc_cbparam_status_get(swigCPtr, this);
  }

  public void setCode(int value) {
    XviJNI.pjsip_regc_cbparam_code_set(swigCPtr, this, value);
  }

  public int getCode() {
    return XviJNI.pjsip_regc_cbparam_code_get(swigCPtr, this);
  }

  public void setReason(pj_str_t value) {
    XviJNI.pjsip_regc_cbparam_reason_set(swigCPtr, this, pj_str_t.getCPtr(value), value);
  }

  public pj_str_t getReason() {
    long cPtr = XviJNI.pjsip_regc_cbparam_reason_get(swigCPtr, this);
    return (cPtr == 0) ? null : new pj_str_t(cPtr, false);
  }

  public void setRdata(SWIGTYPE_p_pjsip_rx_data value) {
    XviJNI.pjsip_regc_cbparam_rdata_set(swigCPtr, this, SWIGTYPE_p_pjsip_rx_data.getCPtr(value));
  }

  public SWIGTYPE_p_pjsip_rx_data getRdata() {
    long cPtr = XviJNI.pjsip_regc_cbparam_rdata_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_pjsip_rx_data(cPtr, false);
  }

  public void setExpiration(int value) {
    XviJNI.pjsip_regc_cbparam_expiration_set(swigCPtr, this, value);
  }

  public int getExpiration() {
    return XviJNI.pjsip_regc_cbparam_expiration_get(swigCPtr, this);
  }

  public void setContact_cnt(int value) {
    XviJNI.pjsip_regc_cbparam_contact_cnt_set(swigCPtr, this, value);
  }

  public int getContact_cnt() {
    return XviJNI.pjsip_regc_cbparam_contact_cnt_get(swigCPtr, this);
  }

  public void setContact(SWIGTYPE_p_p_pjsip_contact_hdr value) {
    XviJNI.pjsip_regc_cbparam_contact_set(swigCPtr, this, SWIGTYPE_p_p_pjsip_contact_hdr.getCPtr(value));
  }

  public SWIGTYPE_p_p_pjsip_contact_hdr getContact() {
    long cPtr = XviJNI.pjsip_regc_cbparam_contact_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_pjsip_contact_hdr(cPtr, false);
  }

  public pjsip_regc_cbparam() {
    this(XviJNI.new_pjsip_regc_cbparam(), true);
  }

}
