/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.phonex.xv;

public class pjsua_call_setting {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected pjsua_call_setting(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(pjsua_call_setting obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        XviJNI.delete_pjsua_call_setting(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setFlag(long value) {
    XviJNI.pjsua_call_setting_flag_set(swigCPtr, this, value);
  }

  public long getFlag() {
    return XviJNI.pjsua_call_setting_flag_get(swigCPtr, this);
  }

  public void setReq_keyframe_method(long value) {
    XviJNI.pjsua_call_setting_req_keyframe_method_set(swigCPtr, this, value);
  }

  public long getReq_keyframe_method() {
    return XviJNI.pjsua_call_setting_req_keyframe_method_get(swigCPtr, this);
  }

  public void setAud_cnt(long value) {
    XviJNI.pjsua_call_setting_aud_cnt_set(swigCPtr, this, value);
  }

  public long getAud_cnt() {
    return XviJNI.pjsua_call_setting_aud_cnt_get(swigCPtr, this);
  }

  public void setVid_cnt(long value) {
    XviJNI.pjsua_call_setting_vid_cnt_set(swigCPtr, this, value);
  }

  public long getVid_cnt() {
    return XviJNI.pjsua_call_setting_vid_cnt_get(swigCPtr, this);
  }

  public pjsua_call_setting() {
    this(XviJNI.new_pjsua_call_setting(), true);
  }

}
