/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.phonex.xv;

public class pjsua_reg_info {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected pjsua_reg_info(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(pjsua_reg_info obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        XviJNI.delete_pjsua_reg_info(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setCbparam(pjsip_regc_cbparam value) {
    XviJNI.pjsua_reg_info_cbparam_set(swigCPtr, this, pjsip_regc_cbparam.getCPtr(value), value);
  }

  public pjsip_regc_cbparam getCbparam() {
    long cPtr = XviJNI.pjsua_reg_info_cbparam_get(swigCPtr, this);
    return (cPtr == 0) ? null : new pjsip_regc_cbparam(cPtr, false);
  }

  public void setRegc(SWIGTYPE_p_pjsip_regc value) {
    XviJNI.pjsua_reg_info_regc_set(swigCPtr, this, SWIGTYPE_p_pjsip_regc.getCPtr(value));
  }

  public SWIGTYPE_p_pjsip_regc getRegc() {
    long cPtr = XviJNI.pjsua_reg_info_regc_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_pjsip_regc(cPtr, false);
  }

  public void setRenew(int value) {
    XviJNI.pjsua_reg_info_renew_set(swigCPtr, this, value);
  }

  public int getRenew() {
    return XviJNI.pjsua_reg_info_renew_get(swigCPtr, this);
  }

  public pjsua_reg_info() {
    this(XviJNI.new_pjsua_reg_info(), true);
  }

}
