/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.phonex.xv;

public class SignCallback {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected SignCallback(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SignCallback obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        XviJNI.delete_SignCallback(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    XviJNI.SignCallback_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    XviJNI.SignCallback_change_ownership(this, swigCPtr, true);
  }

  public int sign(esignInfo_t sdata, hashReturn_t hash) {
    return (getClass() == SignCallback.class) ? XviJNI.SignCallback_sign(swigCPtr, this, esignInfo_t.getCPtr(sdata), sdata, hashReturn_t.getCPtr(hash), hash) : XviJNI.SignCallback_signSwigExplicitSignCallback(swigCPtr, this, esignInfo_t.getCPtr(sdata), sdata, hashReturn_t.getCPtr(hash), hash);
  }

  public int verifySign(esignInfo_t sdata, String sign, String desc) {
    return (getClass() == SignCallback.class) ? XviJNI.SignCallback_verifySign(swigCPtr, this, esignInfo_t.getCPtr(sdata), sdata, sign, desc) : XviJNI.SignCallback_verifySignSwigExplicitSignCallback(swigCPtr, this, esignInfo_t.getCPtr(sdata), sdata, sign, desc);
  }

  public SignCallback() {
    this(XviJNI.new_SignCallback(), true);
    XviJNI.SignCallback_director_connect(this, swigCPtr, swigCMemOwn, false);
  }

}

