/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.phonex.xv;

public interface XviConstants {
  public final static pjsua_callback WRAPPER_CALLBACK_STRUCT = new pjsua_callback(XviJNI.WRAPPER_CALLBACK_STRUCT_get(), false);
  public final static int PJ_SUCCESS = XviJNI.PJ_SUCCESS_get();
  public final static int PJ_TRUE = XviJNI.PJ_TRUE_get();
  public final static int PJ_FALSE = XviJNI.PJ_FALSE_get();
  public final static int PJMEDIA_TONEGEN_LOOP = XviJNI.PJMEDIA_TONEGEN_LOOP_get();
  public final static int PJMEDIA_TONEGEN_NO_LOCK = XviJNI.PJMEDIA_TONEGEN_NO_LOCK_get();

  public final static String EESIGN_HDR = XviJNI.EESIGN_HDR_get();
  public final static String EESIGN_DESC_HDR = XviJNI.EESIGN_DESC_HDR_get();
  public final static int EESIGN_FLAG_DROP_PACKET = XviJNI.EESIGN_FLAG_DROP_PACKET_get();
  public final static int DISABLED_FOR_TICKET_1185 = XviJNI.DISABLED_FOR_TICKET_1185_get();
  public final static int PJSUA_ACC_MAX_PROXIES = XviJNI.PJSUA_ACC_MAX_PROXIES_get();
  public final static int PJSUA_DEFAULT_SRTP_SECURE_SIGNALING = XviJNI.PJSUA_DEFAULT_SRTP_SECURE_SIGNALING_get();
  public final static int PJSUA_ADD_ICE_TAGS = XviJNI.PJSUA_ADD_ICE_TAGS_get();
  public final static int PJSUA_ACQUIRE_CALL_TIMEOUT = XviJNI.PJSUA_ACQUIRE_CALL_TIMEOUT_get();
  public final static int PJSUA_HAS_VIDEO = XviJNI.PJSUA_HAS_VIDEO_get();
  public final static int PJSUA_VID_REQ_KEYFRAME_INTERVAL = XviJNI.PJSUA_VID_REQ_KEYFRAME_INTERVAL_get();
  public final static int PJSUA_MAX_ACC = XviJNI.PJSUA_MAX_ACC_get();
  public final static int PJSUA_REG_INTERVAL = XviJNI.PJSUA_REG_INTERVAL_get();
  public final static int PJSUA_UNREG_TIMEOUT = XviJNI.PJSUA_UNREG_TIMEOUT_get();
  public final static int PJSUA_DEFAULT_ACC_PRIORITY = XviJNI.PJSUA_DEFAULT_ACC_PRIORITY_get();
  public final static int PJSUA_UNPUBLISH_MAX_WAIT_TIME_MSEC = XviJNI.PJSUA_UNPUBLISH_MAX_WAIT_TIME_MSEC_get();
  public final static int PJSUA_REG_RETRY_INTERVAL = XviJNI.PJSUA_REG_RETRY_INTERVAL_get();
  public final static int PJSUA_REG_USE_OUTBOUND_PROXY = XviJNI.PJSUA_REG_USE_OUTBOUND_PROXY_get();
  public final static int PJSUA_REG_USE_ACC_PROXY = XviJNI.PJSUA_REG_USE_ACC_PROXY_get();
  public final static int PJSUA_MAX_CALLS = XviJNI.PJSUA_MAX_CALLS_get();
  public final static int PJSUA_MAX_VID_WINS = XviJNI.PJSUA_MAX_VID_WINS_get();
  public final static int PJSUA_XFER_NO_REQUIRE_REPLACES = XviJNI.PJSUA_XFER_NO_REQUIRE_REPLACES_get();
  public final static int PJSUA_MAX_BUDDIES = XviJNI.PJSUA_MAX_BUDDIES_get();
  public final static int PJSUA_PRES_TIMER = XviJNI.PJSUA_PRES_TIMER_get();
  public final static int PJSUA_MEDIA_HAS_PJMEDIA = XviJNI.PJSUA_MEDIA_HAS_PJMEDIA_get();
  public final static int PJSUA_THIRD_PARTY_STREAM_HAS_GET_INFO = XviJNI.PJSUA_THIRD_PARTY_STREAM_HAS_GET_INFO_get();
  public final static int PJSUA_THIRD_PARTY_STREAM_HAS_GET_STAT = XviJNI.PJSUA_THIRD_PARTY_STREAM_HAS_GET_STAT_get();
  public final static int PJSUA_MAX_CONF_PORTS = XviJNI.PJSUA_MAX_CONF_PORTS_get();
  public final static int PJSUA_DEFAULT_CLOCK_RATE = XviJNI.PJSUA_DEFAULT_CLOCK_RATE_get();
  public final static int PJSUA_DEFAULT_AUDIO_FRAME_PTIME = XviJNI.PJSUA_DEFAULT_AUDIO_FRAME_PTIME_get();
  public final static int PJSUA_DEFAULT_CODEC_QUALITY = XviJNI.PJSUA_DEFAULT_CODEC_QUALITY_get();
  public final static int PJSUA_DEFAULT_ILBC_MODE = XviJNI.PJSUA_DEFAULT_ILBC_MODE_get();
  public final static int PJSUA_DEFAULT_EC_TAIL_LEN = XviJNI.PJSUA_DEFAULT_EC_TAIL_LEN_get();
  public final static int PJSUA_MAX_PLAYERS = XviJNI.PJSUA_MAX_PLAYERS_get();
  public final static int PJSUA_MAX_RECORDERS = XviJNI.PJSUA_MAX_RECORDERS_get();
  public final static int HCODE_MESSAGE = XviJNI.HCODE_MESSAGE_get();
  public final static int HCODE_NOT_SUPPORTED = XviJNI.HCODE_NOT_SUPPORTED_get();
}
